#!/bin/bash
#
set -e
set -x
#
# Create bash profile script
#
cat <<'SCRIPT' >/root/.bash_profile
#!/bin/bash
#
export PS1="\h(bash)# "
echo
echo "Use vtysh to connect to FRR daemon"
echo
SCRIPT
#
# This is an artifact of unknown provenance that should be removed in a year or two (= 2026/2027)
#
# FRR controls these parameters with 'ip forwarding' and 'ipv6 forwarding' commands
#
sysctl -w net.ipv4.ip_forward=1
sysctl -w net.ipv6.conf.all.forwarding=0
#
# Try to create the management VRF if netlab_mgmt_vrf is set. The VRF module has to be loaded
# and the container has to have eth0 device
#
if grep vrf /proc/modules && ip link show dev eth0; then
  #
  # Get the current next hop for the default route
  #
  def_nh=$(ip route list default|awk '{ print $3 }')
  #
  # Create the management VRF and add eth0 to it
  #
  if [ ! -e /sys/devices/virtual/net/mgmt ]; then
    ip link add mgmt type vrf table 42
  fi
  ip link set mgmt up
  sysctl -qw net.ipv6.conf.eth0.keep_addr_on_down=1
  ip link set eth0 master mgmt
  #
  # Reinstall the default route if we had it before
  #
  if [[ -n "$def_nh" ]]; then
    ip route add 0.0.0.0/0 vrf mgmt via $def_nh
  fi
fi
#
# Enable FRR modules (if not using containerlab bind-mounted /etc/frr/daemons)
#

# Set system defaults
#
# Send ARP requests from a sane source IP address
#
sysctl -w net.ipv4.conf.all.arp_announce=2

#
# Create loopbacks, stub and lag/bond devices
#
if [ ! -e /sys/class/net/lo ]; then
  if [ ! -e /sys/devices/virtual/net/lo ]; then
    ip link add lo type dummy
    ip link set dev lo up
  fi
fi

# Disable IPv6 (for IPv4-only interfaces) or SLAAC (if the device is a router)
#
ip link set eth1 down
sysctl -qw net.ipv6.conf.eth1.disable_ipv6=1
ip link set dev eth1 mtu 1500
ip link set eth1 up
ip link set eth2 down
sysctl -qw net.ipv6.conf.eth2.disable_ipv6=1
ip link set dev eth2 mtu 1500
ip link set eth2 up

#
# Add vtysh.conf file
echo "service integrated-vtysh-config" >/etc/frr/vtysh.conf

#
# Rest of initial configuration done through VTYSH
#
cat >/tmp/config <<CONFIG
hostname frr3
!
log file /tmp/logging

!
ip forwarding
vrf mgmt
 exit-vrf
!
frr defaults datacenter
!
interface lo
 no shutdown
 ip address 10.0.0.3/32
!
interface eth1
 no shutdown
 description frr3 -> frr2
 ip address 10.1.0.6/30
!
interface eth2
 no shutdown
 description frr3 -> frr4
 ip address 10.1.0.9/30
!
do write
CONFIG
vtysh -f /tmp/config
!
exit 0