#!/bin/sh
#
# This script contains the 'ip' commands needed to set up container
# interfaces and route table. It's executed within the container
# network namespace on the container host.
#
#  /etc/hosts file is generated as a clab bind.
#
set -e

### One-Shot configuration (non-Ubuntu VM or container)
#
# Send ARP requests from a sane source IP address
sysctl -w net.ipv4.conf.all.arp_announce=2

#
# Enable or disable IPv4 and IPv6 forwarding
#
sysctl -w net.ipv4.ip_forward=0
sysctl -w net.ipv6.conf.all.forwarding=0

#
# Interface addressing, create any bond devices
#
ip link set dev eth1 up
set +e
ip addr del 172.16.0.5/24 dev eth1 2>/dev/null
set -e
ip addr add 172.16.0.5/24 dev eth1
sysctl -w net.ipv6.conf.eth1.disable_ipv6=1
ip link set dev eth1 mtu 1500

