#!/bin/sh
#
# Add static routes (usually IPv4 routes pointing to the first usable gateway)
#
#
echo Removing existing IPv4 routes
while ip route del 172.16.0.0/16 2>/dev/null; do
  : ; done
while ip route del 10.0.0.0/24 2>/dev/null; do
  : ; done
while ip route del 10.1.0.0/16 2>/dev/null; do
  : ; done
while ip route del 10.2.0.0/24 2>/dev/null; do
  : ; done
#
#
#
echo Adding direct static routes
ip route add 172.16.0.0/16 via 172.16.1.4 dev eth1 protocol static
ip route add 10.0.0.0/24 via 172.16.1.4 dev eth1 protocol static
ip route add 10.1.0.0/16 via 172.16.1.4 dev eth1 protocol static
ip route add 10.2.0.0/24 via 172.16.1.4 dev eth1 protocol static
